services:
  web:
    build: .
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - web



  mysql:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5



volumes:
  mysql_data: