# Generated by Django 5.2.1 on 2025-06-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('technology', models.CharField(max_length=50)),
                ('plmn_id', models.CharField(blank=True, max_length=20, null=True)),
                ('lac', models.CharField(blank=True, max_length=20, null=True)),
                ('rac', models.CharField(blank=True, max_length=20, null=True)),
                ('tac', models.CharField(blank=True, max_length=20, null=True)),
                ('cell_id', models.CharField(blank=True, max_length=50, null=True)),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('rsrp', models.FloatField(blank=True, null=True)),
                ('rsrq', models.FloatField(blank=True, null=True)),
                ('rscp', models.FloatField(blank=True, null=True)),
                ('rx_lev', models.FloatField(blank=True, null=True)),
                ('ec_no', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
