# Generated by Django 5.2.1 on 2025-06-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='technology',
            new_name='networkType',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='plmn_id',
            new_name='pinnId',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='recorded_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='arfcn',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='cell_id',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='ec_no',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='rac',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='rscp',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='rx_lev',
        ),
        migrations.AddField(
            model_name='measurement',
            name='cellIdentity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='signalStrengthDbm',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='lac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='rsrp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='rsrq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='tac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
