# Generated by Django 5.2.1 on 2025-06-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_rename_technology_measurement_networktype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
