# Generated by Django 5.2.1 on 2025-06-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_alter_measurement_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='measurement',
            table='Measurement',
        ),
    ]
