# Generated by Django 5.2.1 on 2025-06-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_alter_measurement_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurement',
            new_name='cc_measurement',
        ),
        migrations.AlterModelTable(
            name='cc_measurement',
            table=None,
        ),
    ]
