# Generated by Django 5.2.1 on 2025-06-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0005_rename_measurement_cc_measurement_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cc_measurement',
            new_name='Measurement',
        ),
    ]
