# Generated by Django 5.2.1 on 2025-07-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0006_rename_cc_measurement_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('hostname', models.CharField(max_length=100)),
                ('resolvedIpAddress', models.CharField(max_length=45)),
                ('wasSuccessful', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('fileSizeInBytes', models.BigIntegerField(blank=True, null=True)),
                ('durationInMs', models.BigIntegerField(blank=True, null=True)),
                ('speedMbps', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('host', models.CharField(max_length=1000)),
                ('responseTimeMs', models.FloatField()),
                ('wasSuccessful', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('fileSizeInBytes', models.BigIntegerField(blank=True, null=True)),
                ('durationInMs', models.BigIntegerField(blank=True, null=True)),
                ('speedMbps', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=1000)),
                ('responseTimeMs', models.BigIntegerField(blank=True, null=True)),
                ('httpStatusCode', models.IntegerField()),
                ('wasSuccessful', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
