# Generated by Django 5.2.1 on 2025-08-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0007_dns_download_ping_upload_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dns',
            name='resolutionTimeMs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dns',
            name='wasSuccessful',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
